### PR TITLE
[KED-861]  Add versioning to Spark Dataset

### PR DESCRIPTION
**Pull request by i25959341**
## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
Why was this PR created?

This is PR is created in order to add versioning to Spark dataset

## How has this been tested?
What testing strategies have you used?
Original tests are passing and Versioning mechanism should be seperated.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes
- [ ] Assigned myself to the PR

### CODE REVIEW

**Comment by i25959341** [comment]
@921kiyo any chance of a quick initial feedback?

**Comment by 921kiyo** [comment]
@i25959341 Thank you for your contribution and apologise for the late response. For initial feedback, 

1. I can see you added `DataFrameArgs` class, which I believe is not necessary to implement versioning functionality. We would like to keep `load_args` and `save_args` for consistency with other existing datasets. (If the reason was because the linter was complaining too many arguments, you can disable the linter warning).

2. When you implement the versioning, you have to add unit tests for versioned datasets. See how the unit tests were done for other versioned dataset ([TestExcelLocalDataSetVersioned](https://github.com/quantumblacklabs/kedro/blob/c2d3c55b693e7e2eb5360043dfb62260df04663f/tests/io/test_excel_local.py#L88) for example).

Feel free to ask me any questions :)  I will try to respond more quickly.

**Comment by DmitriiDeriabinQB** [comment]
@i25959341 thanks again for your contribution! Just to add to @921kiyo's comment, the tricky bit about versioning the `SparkDataSet` is that it should reliably work on all filesystems supported by `SparkDataSet`, including at least the following:
* local filesystem `file://`
* s3 filesystem `s3a://`
* HDFS `hdfs://`

**Comment by i25959341** [comment]
amazing, will get it down this weekend!

**Comment by i25959341** [comment]
added a bit more basic tests @921kiyo 

 @DmitriiDeriabinQB  can you elaborate a bit more? I thought that should be important regardless of versioning? Maybe testing saving and loading VersionedData under all these files system?

**Comment by DmitriiDeriabinQB** [comment]
@i25959341 I meant that there should be an extra care when enabling versioning for this dataset, since we're changing the filename provided. For most of the datasets it's not an issue, however it may break SparkDataSet for some file systems and/or file formats, which needs to be tested.

**Comment by i25959341** [comment]
Gotcha!

**Comment by i25959341** [comment]
This is quite a bit more tricky than I thought, it seems like we need some custom logic to deal with different with filesystem, do I also need to how to deal with different filesystem in a bucket?? locally vs s3? When we are dealing with s3, so I have to take care of the credential as well?

Or is there a simpler solution? I feel like it might better to create a seperate issue and tackle this seperately.

**Comment by karlsonthisisbud** [comment]
@DmitriiDeriabinQB  @921kiyo

**Comment by DmitriiDeriabinQB** [comment]
@i25959341 Thanks again for your contribution! We've decided to take this one over and finish it internally (obviously, adding yourself into the collaborators list). I will let you know when the changes are merged. Thank you for your work and hope to see more of it in the future!

**Comment by DmitriiDeriabinQB** [comment]
Resolved in af1186204bd6d6b7dd9b6ac6e36f6c4f66961879

**Pull request closed without merging**
