### PR TITLE
[KED-950] Turn on the branch coverage for unit tests

### PR DESCRIPTION
**Pull request by Cheukting**
## Description
According issue #243 branch test on coverage needed to be turned on

## Development notes
- branch test has been added on .coveragerc
- Adding test to bump coverage back to 100% (WIP)

## Checklist

- [ ] Read the [contributing](/CONTRIBUTING.md) guidelines
- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [X] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by 921kiyo** [comment]
@Cheukting Thank you for working on this! Let us know if you need any help/questions on this :)

**Comment by neomatrix369** [comment]
@Cheukting proud of your work! Always learning so quickly!

**Comment by yetudada** [comment]
Hey @Cheukting 😄 We want to review your PR and merge it in for the next release. Is it ready to come out of draft mode?

**Comment by Cheukting** [comment]
Hey @yetudada sorry for leaving it open for so long. I am afraid there are too many tests (more than I can handle) that are needed to bump the new coverage to 100% Please feel free to assign it to someone else or close if you see fit.

**Comment by neomatrix369** [comment]
> Hey @yetudada sorry for leaving it open for so long. I am afraid there are too many tests (more than I can handle) that are needed to bump the new coverage to 100% Please feel free to assign it to someone else or close it if you see fit.

I'm happy to help but sounds like it's many hands needed to help finish the task.

@Cheukting do you mind zipping the code-coverage folder generated by `coverage` or `pycov` and share it here so I can take a quick look at it and find low-hanging fruits and the inflection points.

**Comment by Cheukting** [comment]
@neomatrix369 can you just pull my commits?

**Comment by mzjp2** [comment]
You should be able to see the coverage output here: https://circleci.com/gh/quantumblacklabs/kedro/8974

**Comment by neomatrix369** [comment]
> @neomatrix369 can you just pull my commits?

I have cloned your pull request now, thanks. I'll take it from here.

**Comment by neomatrix369** [comment]
> You should be able to see the coverage output here: https://circleci.com/gh/quantumblacklabs/kedro/8974

@mzjp2  I don't see a coverage `html` or `xml` report generated after the tests finish, this is useful for local/remote machine consumption. Happy to use the link you shared in the meanwhile.

**Comment by mzjp2** [comment]
> > You should be able to see the coverage output here: https://circleci.com/gh/quantumblacklabs/kedro/8974
> 
> @mzjp2 I don't see a coverage `html` or `xml` report generated after the tests finish, this is useful for local/remote machine consumption. Happy to use the link you shared in the meanwhile.

Gotcha. If you run `make test` yourself locally it should generate a xml report (and a `.coverage` file too, I think?) but you're right that on CI it just shows the CLI output (it does generate the report but we don't surface it as an artifact on our CI build).

**Comment by neomatrix369** [comment]
> > > You should be able to see the coverage output here: https://circleci.com/gh/quantumblacklabs/kedro/8974
> > 
> > 
> > @mzjp2 I don't see a coverage `html` or `xml` report generated after the tests finish, this is useful for local/remote machine consumption. Happy to use the link you shared in the meanwhile.
> 
> Gotcha. If you run `make test` yourself locally it should generate a xml report (and a `.coverage` file too, I think?) but you're right that on CI it just shows the CLI output (it does generate the report but we don't surface it as an artifact on our CI build).

No worries, I'll take care of it and see what I can do, I have done something similar in the past, a HTML based report is a lot more productive to work with, and we can close the PR quicker ;)

**Comment by mzjp2** [comment]
I'll go ahead and close this for now, seeing as the work has been overtaken and done in #327 -- thanks all! :)

**Pull request closed without merging**
