### PR TITLE
[KED-1514] Add `--check-only` option to verify code is linted

### LINKED ISSUE #289: [KED-1514] Add `--check-only` option to verify code is linted
## Description / Context
The way it’s written, `kedro lint` does not "work" as part of a CI process. You run `kedro lint` as a build step, it will see incorrectly sorted imports or unblacked code and fix them then and there--on the build image--and pass the build step.

If `kedro lint` isn’t intended to be used in CI processes, the current implementation is sufficient. However, I would argue that including `kedro lint` in a CI process is a common way of using it (especially at QuantumBlack, because old versions of KernelAI used it as such). In that case, my suggestion would be to have a `kedro lint --check-only` option that you can use in builds.

(synthesized from a Slack conversation with @lorenabalan)

### PR DESCRIPTION
**Pull request by deepyaman**
## Description
Close #289.

~~Based on my experience using the `lint` command provided by Kedro (and pre-OS KernelAI), `kedro lint` is used to verify that code meets our coding standards. Aligning our code with said standards is done locally via `pre-commit`, IDE, or other means. Spoke to some other colleagues, and they share this experience.~~

~~We use `kedro lint` and other commands from `kedro_cli.py` in our CI process. This way of working was also reflected in the `.circleci/config.yml` shipped with KernelAI. In a CI process, it makes no sense for the code to be modified on the build image--because it has no effect, and especially since the build doesn't even fail.~~

## Development notes
~~Run on multiple real-world projects,~~ tested on a project I configured just now.

## Checklist

- [x] Read the [contributing](../CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](../RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by lorenabalan** [comment]
Hi @deepyaman ! I'm having a little trouble following this.
> it makes no sense for the code to be modified on the build image--because it has no effect, and especially since the build doesn't even fail.

For example, we have it so that the build fails if changes need to be made. It's also very useful at development time - when you run the command you want `isort` and `black` to actually change the files, otherwise it's really annoying to have to manually go through them one by one. As an aside, precommit hooks are not necessarily enough, you can easily still bypass them using `-n`.

**Comment by deepyaman** [comment]
@lorenabalan I have modified my PR to add the `--check-only` option, as discussed. :)

**Comment by deepyaman** [comment]
> Does this need a test or an additional case in an existing test?

I can add tests, but I can't find the existing ones for this part of the cli... can you help me? 🙏

**Comment by mzjp2** [comment]
> > Does this need a test or an additional case in an existing test?
> 
> I can add tests, but I can't find the existing ones for this part of the cli... can you help me? 🙏

Should be here: https://github.com/quantumblacklabs/kedro/blob/57cf26a4ae9f11e942cd630dbb4dda71e1edf034/tests/template/test_kedro_cli.py#L347 😄

**Comment by deepyaman** [comment]
> > > Does this need a test or an additional case in an existing test?
> > 
> > 
> > I can add tests, but I can't find the existing ones for this part of the cli... can you help me? 🙏
> 
> Should be here:
> 
> https://github.com/quantumblacklabs/kedro/blob/57cf26a4ae9f11e942cd630dbb4dda71e1edf034/tests/template/test_kedro_cli.py#L347
> 
> 😄

Ah! Under `template`. And I searched for `test_lint` instead of `TestLint` lol.

**Comment by deepyaman** [comment]
@mzjp2 Tests added (or parametrized, to be more accurate), sir!

I didn't bother explicitly testing `--check-only` (alongside `-c`), as that seemed more like a test of `click`.

**Comment by mzjp2** [comment]
> @mzjp2 Tests added (or parametrized, to be more accurate), sir!
> 
> I didn't bother explicitly testing `--check-only` (alongside `-c`), as that seemed more like a test of `click`.



> @mzjp2 Tests added (or parametrized, to be more accurate), sir!
> 
> I didn't bother explicitly testing `--check-only` (alongside `-c`), as that seemed more like a test of `click`.

It's also a test to make sure that things fail if someone accidentally removes the `--check-only` option at some point, but I'm not fussed. Looks good, will approve and merge. Thank you for the contribution! 😀

**Comment by lorenabalan** [comment]
I'll take over this to get around the unhappy fork.

**Comment by lorenabalan** [comment]
Closing this, addressed in https://github.com/quantumblacklabs/kedro/commit/8bfa0a8ce0e3bef194ba8d4ca682becf8accdc24. Many thanks!!

**Pull request closed without merging**
