### PR TITLE
Fix a kedro install issue with conda's environment.yml file

### PR DESCRIPTION
**Pull request by bnmerchant**
## Description
I fixed an issue where `kedro install` would not install packages from an environment.yml file. See #24 

## Development notes
The function call to create a conda environment using `kedro install` was fixed to support a standard environment.yml file. It can also update an existing environment using `kedro install` if environment.yml gains or loses dependencies.

## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [x] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by 921kiyo — APPROVED** [review]
Thank you for the fix!

**Review by limdauto — APPROVED** [review]
LGTM!

**Comment by yetudada** [comment]
Thank you so much for this fix @bnmerchant! I'll need your help with one more change in order to accept this PR. You need to check the tick box underneath the Notice on the PR text and then we'll be able to merge your change in.

**Comment by lorenabalan** [comment]
Thank you so much @bnmerchant for contributing to Kedro! We've released another version yesterday so now the release notes here are in the wrong place, but I'll go ahead and correct it in a separate PR. Hope to see you come back here soon! :)

**Pull request merged**
