### PR TITLE
Improved kedro-neptune description

### PR DESCRIPTION
**Pull request by jakubczakon**
Added some information to the Kedro-neptune plugging description to give readers a better picture of what it actually does.

## Description
Updated kedro-neptune description. 
 
## Development notes
Added short information bout what kedro-neptune will actually do for kedro users and described what they will find in the documentation on the Neptune side. 
## Checklist

- [v] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [v] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [v] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [v] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by yetudada — APPROVED** [review]
Thanks for adding this additional detail @jakubczakon! 🚀

**Comment by datajoely** [comment]
Hi @jakubczakon - do you want to mark this ready for review? I'm pretty sure it can go in as is once marked.

**Comment by jakubczakon** [comment]
Sure thing @datajoely, thanks for reminding me!

**Review by MerelTheisenQB — APPROVED** [review]
👍

**Pull request merged**
