### PR TITLE
[KED-2214] Enable loading config files with Jinja2 templating

### LINKED ISSUE #583: Support Jinja2 templating in config
## Description
With the advent of reusable modular pipelines and namespacing (but even previously with dynamic pipeline creation), it's common to need near-duplicate catalog entries. For example, with primary data models for COVID-19 data in Europe, Asia, and Africa, I may want to reuse the same feature generation and master table creation pipeline, resulting in the following (subset of the) data catalog:

```yaml
europe.case_counts:
  type: pandas.CSVDataSet
  filepath: data/04_feature/europe/cases.csv

europe.death_counts:
europe.demographic_data:
europe.master_table:

asia.case_counts:
  type: pandas.CSVDataSet
  filepath: data/04_feature/asia/cases.csv

asia.death_counts:
asia.demographic_data:
asia.master_table:

africa.case_counts:
  type: pandas.CSVDataSet
  filepath: data/04_feature/africa/cases.csv

africa.death_counts:
africa.demographic_data:
africa.master_table:
```

Having to write it out explicitly is inconvenient (borderline painful) and error-prone. Being forced to use the code API to define configuration is not ideal, either.

## Context
Jinja2 is a widely-used templating language, already supported by the backend technology used by Kedro for configuration parsing, `anyconfig`. Turning it on lets (power) users leverage templating without affecting existing functionality. The above config would become:

```yaml
{% for continent in ['europe', 'asia', 'africa'] %}
{{ continent }}.case_counts:
  type: pandas.CSVDataSet
  filepath: data/04_feature/{{ continent }}/cases.csv

{{ continent }}.death_counts:
{{ continent }}.demographic_data:
{{ continent }}.master_table:
{% endfor %}
```

## Possible Implementation
https://github.com/quantumblacklabs/kedro/pull/578

## Possible Alternatives
Individual users can make this change themselves, but it's annoying. Since [`anyconfig` is imported in `_load_config`](https://github.com/quantumblacklabs/kedro/blob/0.16.5/kedro/config/config.py#L208), it can't be easily monkeypatched and requires redefining/retesting a lot of functionality. For example, from my current project:

`src/package_name/run.py`:
```python
...

def _load_config(config_files: List[Path]) -> Dict[str, Any]:
    """Recursively load all configuration files, which satisfy
    a given list of glob patterns from a specific path.

    Args:
        config_files: Configuration files sorted in the order of precedence.

    Raises:
        ValueError: If 2 or more configuration files contain the same key(s).

    Returns:
        Resulting configuration dictionary.

    """
    # for performance reasons
    import anyconfig  # pylint: disable=import-outside-toplevel

    config = {}
    keys_by_filepath = {}  # type: Dict[Path, AbstractSet[str]]

    def _check_dups(file1: Path, conf: Dict[str, Any]) -> None:
        dups = set()
        for file2, keys in keys_by_filepath.items():
            common = ", ".join(sorted(conf.keys() & keys))
            if common:
                if len(common) > 100:
                    common = common[:100] + "..."
                dups.add("{}: {}".format(str(file2), common))

        if dups:
            msg = "Duplicate keys found in {0} and:\n- {1}".format(
                file1, "\n- ".join(dups)
            )
            raise ValueError(msg)

    for config_file in config_files:
        cfg = {
            k: v
            for k, v in anyconfig.load(config_file, ac_template=True).items()
            if not k.startswith("_")
        }
        _check_dups(config_file, cfg)
        keys_by_filepath[config_file] = cfg.keys()
        config.update(cfg)
    return config


class ProjectContext(KedroContext):
    ...

    def _create_config_loader(self, conf_paths: Iterable[str]) -> TemplatedConfigLoader:
        import kedro.config.config

        kedro.config.config._load_config = _load_config
        return TemplatedConfigLoader(conf_paths, globals_pattern="*globals.yml")
```

`src/tests/test_run.py`:
```python
@pytest.fixture
def project_context(mocker):
    # Don't configure the logging module. If it's configured, tests that
    # check logs using the ``caplog`` fixture depend on execution order.
    mocker.patch.object(ProjectContext, "_setup_logging")

    return ProjectContext(str(Path.cwd()))


def _write_yaml(filepath: Path, config: Dict, preamble: str = "", postamble: str = ""):
    filepath.parent.mkdir(parents=True, exist_ok=True)
    yaml_str = yaml.dump(config)
    filepath.write_text(preamble + yaml_str + postamble)


@pytest.fixture
def conf_paths(tmp_path):
    return [str(tmp_path / "base"), str(tmp_path / "local")]


@pytest.fixture
def param_config():
    return {
        "boats": {
            "type": "${boat_data_type}",
            "filepath": "${s3_bucket}/${raw_data_folder}/${boat_file_name}",
            "columns": {
                "id": "${string_type}",
                "name": "${string_type}",
                "top_speed": "${float_type}",
            },
            "rows": 5,
            "users": ["fred", "${write_only_user}"],
        }
    }


@pytest.fixture
def template_config():
    return {
        "s3_bucket": "s3a://boat-and-car-bucket",
        "raw_data_folder": "01_raw",
        "boat_file_name": "boats.csv",
        "boat_data_type": "SparkDataSet",
        "string_type": "VARCHAR",
        "float_type": "FLOAT",
        "write_only_user": "ron",
    }


@pytest.fixture
def proj_catalog_param(tmp_path, param_config):
    proj_catalog = tmp_path / "base" / "catalog.yml"
    _write_yaml(proj_catalog, param_config)


@pytest.fixture
def proj_catalog_param_w_jinja2_for(tmp_path, param_config):
    proj_catalog = tmp_path / "base" / "catalog.yml"
    _write_yaml(
        proj_catalog,
        param_config,
        "{% for boat_type in ['house', 'paddle'] %}\n{{ boat_type }}.",
        "{% endfor %}\n",
    )


@pytest.fixture
def proj_catalog_globals(tmp_path, template_config):
    global_yml = tmp_path / "base" / "globals.yml"
    _write_yaml(global_yml, template_config)


class TestProjectContext:
    def test_project_name(self, project_context):
        assert project_context.project_name == "Engineering Reimagined - Schedule"

    def test_project_version(self, project_context):
        assert project_context.project_version == "0.16.4"

    @pytest.mark.usefixtures("proj_catalog_param", "proj_catalog_globals")
    def test_create_config_loader(self, project_context, tmp_path, conf_paths):
        """Test parameterized config with globals yaml file"""
        (tmp_path / "local").mkdir(exist_ok=True)

        catalog = project_context._create_config_loader(conf_paths).get("catalog*.yml")

        assert catalog["boats"]["type"] == "SparkDataSet"
        assert (
            catalog["boats"]["filepath"] == "s3a://boat-and-car-bucket/01_raw/boats.csv"
        )
        assert catalog["boats"]["columns"]["id"] == "VARCHAR"
        assert catalog["boats"]["columns"]["name"] == "VARCHAR"
        assert catalog["boats"]["columns"]["top_speed"] == "FLOAT"
        assert catalog["boats"]["users"] == ["fred", "ron"]

    @pytest.mark.usefixtures("proj_catalog_param_w_jinja2_for", "proj_catalog_globals")
    def test_create_config_loader_w_jinja2_for(
        self, project_context, tmp_path, conf_paths
    ):
        """Test parameterized config with globals yaml file"""
        (tmp_path / "local").mkdir(exist_ok=True)

        catalog = project_context._create_config_loader(conf_paths).get("catalog*.yml")

        for boat_type in ["house", "paddle"]:
            assert catalog[f"{boat_type}.boats"]["type"] == "SparkDataSet"
            assert (
                catalog[f"{boat_type}.boats"]["filepath"]
                == "s3a://boat-and-car-bucket/01_raw/boats.csv"
            )
            assert catalog[f"{boat_type}.boats"]["columns"]["id"] == "VARCHAR"
            assert catalog[f"{boat_type}.boats"]["columns"]["name"] == "VARCHAR"
            assert catalog[f"{boat_type}.boats"]["columns"]["top_speed"] == "FLOAT"
            assert catalog[f"{boat_type}.boats"]["users"] == ["fred", "ron"]

    @pytest.mark.usefixtures("proj_catalog_globals")
    def test_lots_of_duplicates(self, project_context, tmp_path, conf_paths):
        """Check that the config key starting with `_` are ignored and also
        don't cause a config merge error"""
        data = {str(i): i for i in range(100)}
        _write_yaml(tmp_path / "base" / "catalog1.yml", data)
        _write_yaml(tmp_path / "base" / "catalog2.yml", data)
        (tmp_path / "local").mkdir(parents=True, exist_ok=True)

        conf = project_context._create_config_loader(conf_paths)
        pattern = r"^Duplicate keys found in .*catalog2\.yml and\:\n\- .*catalog1\.yml\: .*\.\.\.$"
        with pytest.raises(ValueError, match=pattern):
            conf.get("**/catalog*")
```

### PR DESCRIPTION
**Pull request by deepyaman**
## Description
Closes #583 

## Development notes
In use on current project

## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [x] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by limdauto — COMMENTED** [review]
Thank you very much. This looks good to me but will hold off merging till next week because I want to discuss this with the team first. ~Out of curiosity, how are you using it in your current project?~ (Sorry I found the linked issue)

**Comment by DmitriiDeriabinQB** [comment]
Hey @deepyaman! Thanks for raising this!

We had an internal discussion about enabling Jinja2 templating when we first prototyped the `ConfigLoader`. However, we realised that it does more harm than good as it renders the configuration into a proper script, which wanted to avoid as it may get out of control _very_ quickly (especially for not so experienced pipeline developers). We wanted the ConfigLoader to work in a straightforward and predictable way.

At the same time, this is useful for more experienced users who know what they are doing and are ready to accept the risks 🙂  So maybe this can be translated into a standalone `JinjaConfigLoader` (similar to `TemplatedConfigLoader`)?

Another option to think about would be some sort of a layered structure, where users can have a catalog blueprint that may contain the template syntax, but that blueprint has then to be 'compiled' by Kedro into a static catalog before run (something similar to `requirements.in` and `requirements.txt` in the project). This is not currently supported by any component of Kedro and would need to be properly designed.

**Comment by deepyaman** [comment]
> So maybe this can be translated into a standalone `JinjaConfigLoader` (similar to `TemplatedConfigLoader`)?

In the "Possible alternatives" section of https://github.com/quantumblacklabs/kedro/issues/583#issue-727512917, I share a snippet where we're using Jinja2 templating with `TemplatedConfigLoader`. I don't really want to add a `TemplatedJinjaConfigLoader` on top of that. One could design some sort of composition structure, but it's not very straightforward.

If I'm going to accept the risks/complications of using this `JinjaConfigLoader`, why not just let me accept the risks with the regular config loader? Nobody's forcing people to start using Jinja2 syntax. If you find a lot of people start using it, maybe it warrants more formal support.

Some other options that work for me:

* Kedro can enable this functionality without advertising it.
* The `anyconfig` import can be moved out of the `_load_config` function so that it's easily monkey-patchable. At least that way you don't have to copy-paste so much code into project repos to enable this functionality. (less preferred)

**Comment by DmitriiDeriabinQB** [comment]
@deepyaman Thanks for the reply.

> The `anyconfig` import can be moved out of the `_load_config` function.

Yes, we will refactor the ConfigLoader so that it's easier to overwrite the call to the backed without the need to rewrite the half of the class.

Additionally, we can set `ac_template=True` for `TemplatedConfigLoader`, so that it supports Jinja2 syntax too.

**Comment by DmitriiDeriabinQB** [comment]
@deepyaman Jinja2 templating has been enabled for `TemplatedConfigLoader` in c466c8aa36488c8fa8d1fe6bb3d5bcde81100e4a and will be released in 0.17.0.

**Comment by lorenabalan** [comment]
Please consider closing this PR in light of https://github.com/quantumblacklabs/kedro/commit/c466c8aa36488c8fa8d1fe6bb3d5bcde81100e4a :)

**Comment by deepyaman** [comment]
> @deepyaman Jinja2 templating has been enabled for `TemplatedConfigLoader` in [c466c8a](https://github.com/quantumblacklabs/kedro/commit/c466c8aa36488c8fa8d1fe6bb3d5bcde81100e4a) and will be released in 0.17.0.

Amazing, thanks!

**Pull request closed without merging**
