### PR TITLE
Keep copy button under the same domain

### PR DESCRIPTION
**Pull request by WaylonWalker**
## Description
This PR is to attempt to correct #580.

## Development notes

I downloaded the `copy-button.svg`, then added `copybutton_image_path ` variable as the [sphinx-copybutton docs](https://sphinx-copybutton.readthedocs.io/en/latest/index.html?highlight=copybutton_image_path%20#use-a-different-copy-button-image) suggested.

I tried to run `make docs` and ran into `[autosummary] failed to import 'kedro.extras.datasets.spark.SparkDataSet': no module named kedro.extras.datasets.spark.SparkDataSet`.

## Checklist

- [X] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by limdauto — APPROVED** [review]
This LGTM but you might need to add a newline at the end of the SVG for the linter to be happy 😅

**Comment by WaylonWalker** [comment]
Added the new line,

Could someone that is setup to build docs locally test this?  I ran into an error with a spark module while trying to build, and was unable to fully test it.

**Comment by stichbury** [comment]
Let me take a look at this tomorrow, Friday 23rd and build it to check all is OK @waylonwalker

**Comment by stichbury** [comment]
> Added the new line,
> 
> Could someone that is setup to build docs locally test this? I ran into an error with a spark module while trying to build, and was unable to fully test it.

I have tested this by building locally, and it works perfectly for me. Thanks!

**Comment by WaylonWalker** [comment]
> I have tested this by building locally, and it works perfectly for me. Thanks!

First Try!

**Review by limdauto — APPROVED** [review]

**Review by lorenabalan — APPROVED** [review]
Thank you! ⭐

**Pull request merged**
