### PR TITLE
Create a Matplotlib Writer that supports versioning 

### PR DESCRIPTION
**Pull request by TomaszKaczmarczyk**
## Description
Modified MatplotlibWriter that supports versioning of datasets. Resolves issue #311.

## Development notes
New class ``MatplotlibVersionedWriter`` created. Tested on both single and multifile plots in local and S3 storages. 

Note: existing class MatplotlibWriter did not support versioning even though it was mentioned in the docs that it is supported.

## Checklist

- [x] Read the [contributing](../CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](../RELEASE.md) file
- [x] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by deepyaman** [comment]
Not quite related, but how does this build work, whereas everything I've done in the past month fail? I checked the branch, and it does point to the AWS images...

**Comment by 921kiyo** [comment]
@deepyaman We are not sure why all of your fork PR are failing for some reasons, whereas other PRs were working fine. We updated AWS credentials for CI in forks, but somehow it's only failing on yours. Could you address the minor fixes in another PR to see if it solves the problem? Otherwise, we will address your changes internally.

**Comment by 921kiyo** [comment]
@TomaszKaczmarczyk Thank you for the PR and addition data versioning to Matplotlib DataSet! We are more than happy to add versioning functionality to this dataset, but instead of creating a new separate dataset, it would be great if you extend our existing MatplotLibWriter class by replacing `AbstractDataSet` with `AbstractVersionedDataSet`, so that there will be no duplication with the dataset classes (see how other datasets implement versioning)? Once it is done, I will review your code :) 

Please let us know if you have any questions!

**Comment by yetudada** [comment]
Hi @TomaszKaczmarczyk! We've taken over this PR to make sure that it's in our next release. You will see that versioning is applied to the existing `MatplotlibWriter` in Kedro 0.16.0. With that in mind, we're going to close this PR but will add you to the list of contributors for your awesome work. Thank you so much for this!

**Pull request closed without merging**
