### PR TITLE
[KED-2931] Remove transfomers

### PR DESCRIPTION
**Pull request by lorenabalan**
## Description

Follow-up to #1020 

## Checklist

- [ ] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by MerelTheisenQB — APPROVED** [review]
👍 👍

**Review by AntonyMilneQB — APPROVED** [review]
I actually think it might be worth translating the memory/time profiling transformers and decorators into hooks as nice examples for the documentation. Like in #723 and #724. But that is for another time.

**Comment by lorenabalan** [comment]
@AntonyMilneQB I think @SajidAlamQB did something like that recently.

**Comment by SajidAlamQB** [comment]
@AntonyMilneQB here is the memory consumption example with hooks: https://kedro.readthedocs.io/en/latest/07_extend_kedro/02_hooks.html#hooks-examples

**Review by SajidAlamQB — APPROVED** [review]

**Pull request merged**
