### PR TITLE
Fix Docs function signature for DryRunner._run

### PR DESCRIPTION
**Pull request by WaylonWalker**
## Description

Kedro passes in a run_id, and throws an error.

## Development notes

This function signature now matches the other runners.

## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/main/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by datajoely** [comment]
You are a star ⭐️ @WaylonWalker thank you for raising this I put this on our backlog just yesterday

**Review by AntonyMilneQB — APPROVED** [review]
Great spot, thanks for doing this @WaylonWalker. I just updated the list of `Args` in the docstring and ran `black` on what you changed.

**Review by datajoely — APPROVED** [review]

**Comment by MerelTheisenQB** [comment]
@WaylonWalker Can you please update this to be merged into `master`? We are in the process of making `main` our default branch, but we aren't quite there yet.

**Comment by WaylonWalker** [comment]
> @WaylonWalker Can you please update this to be merged into `master`? We are in the process of making `main` our default branch, but we aren't quite there yet.

updated to master, I hadn't even noticed main.

**Comment by WaylonWalker** [comment]
> You are a star star @WaylonWalker thank you for raising this I put this on our backlog just yesterday

Thanks @datajoely, I try to fix the easy ones as I spot them otherwise I just forget.

**Pull request merged**
