### PR TITLE
Update image showcasing Kedro-Viz in README.md

### PR DESCRIPTION
**Pull request by ManishS6**
update the image for pipeline visualization generated using Kedro-Viz

## Description

as mentioned in #918
## Development notes

I have updated the image showcasing "A pipeline visualization generated using Kedro-Viz"
## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Review by MerelTheisenQB — COMMENTED** [review]
Thanks for the contribution @ManishS6 😄 

Could you also please delete the original picture here: https://github.com/quantumblacklabs/kedro/blob/master/static/img/pipeline_visualisation.png

and don't forget to add your name to the contributors in the release notes.

**Comment by ManishS6** [comment]
> Thanks for the contribution @ManishS6 😄
> 
> Could you also please delete the original picture here: https://github.com/quantumblacklabs/kedro/blob/master/static/img/pipeline_visualisation.png
> 
> and don't forget to add your name to the contributors in the release notes.

@MerelTheisenQB on it.

**Comment by ManishS6** [comment]
> > Thanks for the contribution @ManishS6 😄
> > Could you also please delete the original picture here: https://github.com/quantumblacklabs/kedro/blob/master/static/img/pipeline_visualisation.png
> > and don't forget to add your name to the contributors in the release notes.
> 
> @MerelTheisenQB on it.

Could you please guide me where should I add my name I think I am lost.

**Comment by MerelTheisenQB** [comment]
> Could you please guide me where should I add my name I think I am lost.

Of course! You should add your name under the contributors section for the upcoming `0.17.6` release here: https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#thanks-for-supporting-contributions

**Review by yetudada — APPROVED** [review]
Thank you so much @ManishS6!

**Comment by ManishS6** [comment]
My pleasure.
By the way, Why did the checks fail even though I didnt do anything with the code.

**Comment by ManishS6** [comment]
@MerelTheisenQB Could you please review my changes.

**Comment by MerelTheisenQB** [comment]
> My pleasure. By the way, Why did the checks fail even though I didnt do anything with the code.

We're seeing failures on our Windows build at the moment and are trying to find a fix. It's not related to any recent changed on Kedro, but sadly it's blocking all of our builds right now 😞

**Review by MerelTheisenQB — APPROVED** [review]
LGTM! 👍  Thanks again for the contribution.

**Pull request merged**
