### PR TITLE
[KED-1171] Kedro CLI command to help catalog cleaning

### PR DESCRIPTION
**Pull request by jiriklein**
## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
The point of this PR is to create a `kedro cli` function that would allow the users to list all _redundant_ catalog entries. This is particularly useful towards the end of a project or during a handover, where project can have hundreds of catalog entries, but some may have been deprecated or replaced. 
At the same time, the diff in the other direction is useful as well, as it allows the users to see which `DataSet`s are considered to be `MemoryDataSet`s and listing those to the user on a `kedro cli` command. 

## How has this been tested?
Testing pending

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [ ] Added tests to cover my changes
- [x] Assigned myself to the PR

### CODE REVIEW

**Comment by tolomea** [comment]
the team needs to discuss but my inclination wold be to put this in the main code, not contrib, and add code to the template kedro_cli to expose it on the command line and pretty print the output

**Comment by jiriklein** [comment]
@tolomea Thank you.
Please let me know if you want me to move the code around. As a user of `kedro`, I think the command could take a shape like this:
```
kedro clean-catalog -h
kedro clean-catalog
kedro clean-catalog --prune
```
respectively for help, pretty-printing and removing redundant datasets (by actually going into the YAML file and deleting relevant lines. But this could (and perhaps should) be raised as separate PR.

**Comment by tolomea** [comment]
I would not do prune at this time, just pretty printing

**Comment by jiriklein** [comment]
@tolomea 
Another point raised by the DE team -> it would be very useful for us to pretty-print `terminus` datasets, i.e. datasets that are outputs but are never used anywhere else. This would be particularly useful for large `SparkDataSets` going from raw -> intermediate (Parquet) and are not used anywhere else. 
Is it okay if I include this in this PR as well?

**Comment by tolomea** [comment]
so the team needs to weigh in, but my view would be to not call it clean but rather something like catalog info and print out whatever is useful in a tidy readable manner

**Comment by lorenabalan** [comment]
Closing this as resolved in [this commit](https://github.com/quantumblacklabs/kedro/commit/30eb0692fac696a971af31de6337412e38105ecd), thank you very much for the suggestion! Please feel free to come back with further improvements/feedback on the functionality.

**Pull request closed without merging**
