### PR TITLE
[KED-1334] Replace ``values`` with recommended ``to_numpy()``

### PR DESCRIPTION
**Pull request by deepyaman**
## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
Why was this PR created?

🐨 

## How has this been tested?
What testing strategies have you used?

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Assigned myself to the PR

### CODE REVIEW

**Comment by ZainPatelQB** [comment]
Am I wrong or is `.to_numpy()` only available in `pandas>=0.24.0`? Our `requirements.txt` has `pandas>=0.23.0`.

**Comment by deepyaman** [comment]
> Am I wrong or is `.to_numpy()` only available in `pandas>=0.24.0`? Our `requirements.txt` has `pandas>=0.23.0`.

Not wrong. Good that you pointed it out.

That being said, if you consider the use of the project template, especially for the example, I think this should still be fair/better. Since `include_example` is catered to completely new users, you'd ~expect~ want them to create a new virtual environment, `kedro install`, and thereby pick up the latest satisfying `pandas>=0.23.0` (with `.to_numpy()` support).

On that note...

The "Hello World" example docs (and [the page they link to](https://kedro.readthedocs.io/en/latest/02_getting_started/03_new_project.html#create-a-new-project-interactively)) don't actually explicitly suggest `kedro install`, etc. workflow. That's covered [here](https://kedro.readthedocs.io/en/latest/03_tutorial/01_workflow.html). Should we change that? @yetudada don't know if you want to opine on the docs question.

**Comment by DmitriiDeriabinQB** [comment]
> `pandas>=0.24.0`

@deepyaman Would you mind bumping the minimum require version of pandas to `0.24.0` in `requirements.txt` and adding a short comment explaining the reason? I guess, it would make sense to make this change in this PR.

> The "Hello World" example docs (and the page they link to) don't actually explicitly suggest kedro install

I believe `kedro install` is mentioned in [this section](https://kedro.readthedocs.io/en/latest/02_getting_started/03_new_project.html#install-project-dependencies) on the same page.

**Comment by deepyaman** [comment]
@DmitriiDeriabinQB Done!

**Comment by deepyaman** [comment]
@lorenabalan Done!

**Pull request merged**
