### PR TITLE
update credentials example for S3 bucket specs

### LINKED ISSUE #539: [KED-2045] Update credentials example for S3 bucket specs
## Wrap your credentials

The section of the docs [Feeding in credentials](https://kedro.readthedocs.io/en/stable/05_data/01_data_catalog.html#feeding-in-credentials) needs to be updated.

Since we are using the `fsspeec` library components to instantiate the filesystem object, credentials will be passed to that call rather than to the underlying AWS SDK directly. Therefore, credentials have to be wrapped into `client_kwargs` for S3 filesystem.  

I.e., `credentials.yml` should look like:
```
dev_s3:
  client_kwargs:
    aws_access_key_id: key
    aws_secret_access_key: secret
```
Instead of:
image

### PR DESCRIPTION
**Pull request by vhawk19**
## Description
Resolves #539 

Update documentation for S3 bucket credentials example
## Development notes

None, only docs/source updated.
## Checklist

- [x ] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x ] Updated the documentation to reflect the code changes
- [x] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [x] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by laisbsc** [comment]
@vhawk19 Awesome! Thanks for this. I just need you to add your name to the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#thanks-for-supporting-contributions-1) and we will be good to go! :)

🎉

**Review by laisbsc — APPROVED** [review]
Looks good to me 👍

**Comment by vhawk19** [comment]
> 
> 
> @vhawk19 Awesome! Thanks for this. Can you please add your name to the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#thanks-for-supporting-contributions-1) and we will be good to go! :)
> 
> 🎉

I was unsure about adding my name to the supporting contributors. This is why I didn't add my name to the list of supporting contributors, however I have done the same now. 

Also, is it okay if they are two different commits? 

This was a great experience!! 😃

**Comment by deepyaman** [comment]
> > @vhawk19 Awesome! Thanks for this. Can you please add your name to the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md#thanks-for-supporting-contributions-1) and we will be good to go! :)
> > 🎉
> 
> I was unsure about adding my name to the supporting contributors. This is why I didn't add my name to the list of supporting contributors, however I have done the same now.

Can you move it to the section for the upcoming release, please? It will be near the top of RELEASE.md.

> Also, is it okay if they are two different commits?

No matter! PRs to Kedro have all their commits squashed (i.e. converted into a single commit) to maintain clean, linear history.

> This was a great experience!! 😃

**Comment by laisbsc** [comment]
@vhawk19 as soon as you address the [comment above](https://github.com/quantumblacklabs/kedro/pull/542#issuecomment-703393716), we will be ready to review and merge. :)

Thanks again for contributing!

**Review by lorenabalan — APPROVED** [review]

**Comment by lorenabalan** [comment]
> @vhawk19 as soon as you address the [comment above](https://github.com/quantumblacklabs/kedro/pull/542#issuecomment-703393716), we will be ready to review and merge. :)
> 
> Thanks again for contributing!

I've gone ahead and done that for you just so I can quickly tidy this up and merge, but for future reference: https://github.com/quantumblacklabs/kedro/pull/542/commits/7f744599c4ed1a499b12abb827be9bd30fe1d8a8

Thank you and hoping to see back here soon!

**Pull request merged**
