### PR TITLE
Update Argo yaml template to include `imagePullPolicy: Always`

### PR DESCRIPTION
**Pull request by 921kiyo**
## Description

I used Argo script from Kedro docs, and it worked out of the box, which is great! One thing that tripped me out (I'm a Kubernetes newbie) was the image was not being updated when the new one was pushed to the registry. So I feel the template yaml should have this explicit so that users can turn this off if they want to. 

Apart from this, everything worked smoothly :) 

See https://kubernetes.io/docs/concepts/containers/images/#updating-images 

## Checklist

- [ ] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by 921kiyo** [comment]
Could anyone review this 1 line PR, please?

**Review by lorenabalan — APPROVED** [review]
Makes sense to me, thank you! ✨

**Comment by 921kiyo** [comment]
@lorenabalan Thank you for approval! Could you also merge the PR as I'm not authorized to do it anymore?

**Comment by lorenabalan** [comment]
> @lorenabalan Thank you for approval! Could you also merge the PR as I'm not authorized to do it anymore?

Ofc, once it gets another approval.

**Review by ignacioparicio — APPROVED** [review]
LGTM, thank you @921kiyo!

**Pull request merged**
