### PR TITLE
added a Dockerfile for production builds

### PR DESCRIPTION
**Pull request by yarncraft**
## Notice

- [X] I acknowledge and agree that, by checking this box and clicking “Submit Pull Request”:

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
To facilitate platform independent builds leveraging the Docker framework. The container is quite large because of the Anaconda libraries, although I reduced them by using MicroConda, I am planning on making a minimal build as well.

## How has this been tested?
By making sure that the Hello World example works. Formal tests are yet to be conducted.

## Checklist

- [X] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes
- [X] Assigned myself to the PR
- [ ] Added `Type` label to the PR

Image
kedro

### CODE REVIEW

**Comment by yetudada** [comment]
Thank you for sending this in @yarncraft! We're going to look into this PR for you. We just need a bit more information from you. Are you trying to deploy Kedro projects or run CI or tests?

**Comment by yarncraft** [comment]
> Thank you for sending this in @yarncraft! We're going to look into this PR for you. We just need a bit more information from you. Are you trying to deploy Kedro projects or run CI or tests?

The purpose of this Dockerfile is to serve as a tool for packing and shipping Kedro projects within containers. A project pipeline can be set up by the use of the Docker Image, so that it can be easily deployed in cloud environments!

**Comment by yarncraft** [comment]
Feel free to move the Dockerfile to another folder, its sole purpose is to facilitate installation for users that do not want install/configure Anaconda/Python/etc. themselves. Make note that the Docker Image is still quite large, an Alpine image would decrease the size (I am trying to construct this as well).

**Comment by yetudada** [comment]
Oh! We have something being released soon, our `kedro-docker` plugin which essentially allows you to package your Kedro projects within Docker containers. It also has additional functionality that allows you to run the Docker containers. I suspect this might cover most of your use case?

**Comment by yarncraft** [comment]
> Oh! We have something being released soon, our `kedro-docker` plugin which essentially allows you to package your Kedro projects within Docker containers. It also has additional functionality that allows you to run the Docker containers. I suspect this might cover most of your use case?

Alright, we are deploying some ML models with kedro back at the campus, I'll be looking forward to the feature, thanks for the support! 👍

**Comment by tsanikgr** [comment]
Thanks for the interest @yarncraft :)

Out of curiosity, which campus are you referring to? (careful not to mention client names here, if you are part of QB!)

**Comment by yarncraft** [comment]
> Thanks for the interest @yarncraft :)
> 
> Out of curiosity, which campus are you referring to? (careful not to mention client names here, if you are part of QB!)

I am currently doing my master's thesis at the Computer Science Engineering faculty of KULeuven, I'm working with Multi Armed Bandits and Uplift Modelling (which is a relatively new Data Science technique for enhancing predictive models). My results need to be reproducible so therefore I'll be using kedro. I'll post some blog articles in the process of how it supports my work!

**Comment by tsanikgr** [comment]
Amazing, we are really excited you are using it!! Please share feedback, we would love to help as much as we can! How did you hear about kedro, if you don't mind me asking?

**Comment by yarncraft** [comment]
I was looking for a way to standardize my pipelines for as they also enhance IT Service Management and could reduce development cost in many workplaces. I saw a blog article on LinkedIn where McKinsey announced your work, it immediately seemed worthwile to take a deeper look. I'll be following up with the development and I'll inspect the source code to see how I potentially can contribute.

_Small note for kedro-docker:_ Alpine Linux Project offers a 5MB bare minimal linux environment to start with. Compared to a 115MB Ubuntu image. Python also has a base image for alpine python:3.6-alpine which is 75MB, comparing to 918MB of the Ubuntu Python image. So for lightweight containers it seems to be a good fit. Furthermore ML prediction jobs could be deployed on Kubernetes Workqueue for faster results!

**Comment by tsanikgr** [comment]
Perfect and thanks for your input! :)

We 'll make sure to tag you when `kedro-docker` is public! Happy coding :)

**Comment by yarncraft** [comment]
Alright, keep up the good work!

**Comment by yetudada** [comment]
Hi @yarncraft! `Kedro-Docker` is out! Let us know what you think: https://github.com/quantumblacklabs/kedro-docker

**Comment by yarncraft** [comment]
> Hi @yarncraft! `Kedro-Docker` is out! Let us know what you think: https://github.com/quantumblacklabs/kedro-docker

Will do! Thanks for the update 👍

**Comment by yarncraft** [comment]
> Hi @yarncraft! `Kedro-Docker` is out! Let us know what you think: https://github.com/quantumblacklabs/kedro-docker

I deployed a quick test run on several VM's, make sure to disclaim on both Kedro and Kedro-Docker that a 64 bit Python version is required in order to pass the install of both kedro and kedro-docker. Otherwise your PyArrow dependency will cause the installation to break on a Windows machine!

Related error: https://stackoverflow.com/questions/55834425/raise-runtimeerrornot-supported-on-32-bit-windows-when-installing-pyarrow

**Comment by yetudada** [comment]
> > Hi @yarncraft! `Kedro-Docker` is out! Let us know what you think: https://github.com/quantumblacklabs/kedro-docker
> 
> I deployed a quick test run on several VM's, make sure to disclaim on both Kedro and Kedro-Docker that a 64 bit Python version is required in order to pass the install of both kedro and kedro-docker. Otherwise your PyArrow dependency will cause the installation to break on a Windows machine!
> 
> Related error: https://stackoverflow.com/questions/55834425/raise-runtimeerrornot-supported-on-32-bit-windows-when-installing-pyarrow

Thank you so much for catching this! I've created a ticket to update our documentation. I hope you've been able to use `kedro-docker` otherwise?

**Comment by yarncraft** [comment]
> > > Hi @yarncraft! `Kedro-Docker` is out! Let us know what you think: https://github.com/quantumblacklabs/kedro-docker
> > 
> > 
> > I deployed a quick test run on several VM's, make sure to disclaim on both Kedro and Kedro-Docker that a 64 bit Python version is required in order to pass the install of both kedro and kedro-docker. Otherwise your PyArrow dependency will cause the installation to break on a Windows machine!
> > Related error: https://stackoverflow.com/questions/55834425/raise-runtimeerrornot-supported-on-32-bit-windows-when-installing-pyarrow
> 
> Thank you so much for catching this! I've created a ticket to update our documentation. I hope you've been able to use `kedro-docker` otherwise?

You're welcome, I've been experimenting with the 64-bit one and it works like expected 🥇 I've published an issue on the kedro-docker regarding a potential lightweight image. As for now your template Dockerfile is still quite large (More info: https://github.com/quantumblacklabs/kedro-docker/issues/5).

**Pull request closed without merging**
