### PR TITLE
Correcting entry in the RELEASE.md file

### PR DESCRIPTION
**Pull request by neomatrix369**
## Description
Docs: corrected previous release notes entry (via PR #266, related to  issue #256)

## Development notes
No code changes, just amending RELEASE.md

## Checklist

- [X] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] ~Opened this PR as a 'Draft Pull Request' if it is work-in-progress~
- [ ] ~Updated the documentation to reflect the code changes~
- [X] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [ ] ~Added tests to cover my changes~

## Notice

- [X] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Any chance of this been merged, its pretty trivial and no code or Kedro documentation changes involved

**Comment by mzjp2** [comment]
Can you fix the conflict before we merge? :)

**Comment by neomatrix369** [comment]
> Can you fix the conflict before we merge? :)

I keep fixing it - they will continue to occur if not merged quickly

**Comment by neomatrix369** [comment]
@mzjp2 just fixed, it's being built now

**Comment by limdauto** [comment]
Closing / Reopening the PR to re-trigger CI.

**Comment by neomatrix369** [comment]
Thanks all for merging this :)

**Pull request merged**
