### PR TITLE
Fix spelling in the community-developed plugins docs

### PR DESCRIPTION
**Pull request by deepyaman**
## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/main/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/main/RELEASE.md) file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by datajoely — APPROVED** [review]

**Comment by deepyaman** [comment]
CircleCI checks aren't triggering, faced this issue several times in the past but now there's no private repo to push to as an alternative. Tried pushing to my fork as well in #1135, but no luck. #1109 (not my PR) seems to face the same issue.

Maybe this can be merged with an override since there's no code changes/it's pretty trivial, but guess this problem will need to be sorted out sooner than later. Think it might be worth checking with CircleCI support, to see if they can diagnose the cause of not running builds in some of these instances?

**Comment by AntonyMilneQB** [comment]
> 

This is annoying... I  was hoping that my recent rewrite of the CircleCI config would magically fix this. I'll make a ticket to investigate this, thanks for mentioning it again.

**Review by AntonyMilneQB — APPROVED** [review]

**Comment by deepyaman** [comment]
@MerelTheisenQB triggers the CI with an empty commit, it runs; I try to do the same (to rerun the Windows build that timed out, because I apparently don't have write access to select "Rerun workflow from failed" in CircleCI), and it's stuck again. 🤮

**Comment by MerelTheisenQB** [comment]
> @MerelTheisenQB triggers the CI with an empty commit, it runs; I try to do the same (to rerun the Windows build that timed out, because I apparently don't have write access to select "Rerun workflow from failed" in CircleCI), and it's stuck again. 🤮

This is so frustrating! We'll have to contact CircleCI support.. Let me trigger it again with an empty commit.

**Review by yetudada — APPROVED** [review]
Thanks for these changes!

**Review by idanov — APPROVED** [review]

**Pull request merged**
