### PR TITLE
FEAT added query to DataCatalog

### PR DESCRIPTION
**Pull request by WaylonWalker**
I have been using an older version of kedro for a few months now.  This
project has grown a large catalog, and I find myself writing out this
simple list comprehension multiple times per day.  So I added this to
part of our load script for jupyter to quickly query for data sets that
I am looking for.

This method will take multiple arguments and return a list of _data_sets
that contain all of the search terms.

Example

```
>>> io.list()
['a_raw_product_id',
'b_int_product_id',
'c_pri_product_id',
'a_raw_procuct_price',
'b_int_procuct_price',
'c_pri_procuct_price', ]

>>> io.query('c_pri')
['c_pri_product_id',
'c_pri_procuct_price',]

>>> io.query('c_pri', 'price')
['c_pri_procuct_price',]

```

## Notice

- [ x] I acknowledge and agree that, by checking this box and clicking “Submit Pull Request”:

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
I have been using kedro for a few months and this feature saves me many kestrokes throughout the day.  It is a feature of convenience, it has no effect in how the pipeline is executed or performs.  This feature only makes it easier to find data sets, particularly in large projects with many data sets.

## How has this been tested?
What testing strategies have you used?

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes
- [x] Assigned myself to the PR
- [x] Added `Type` label to the PR

### CODE REVIEW

**Comment by tsanikgr** [comment]
Hey @WaylonWalker, this is a really useful contribution :) Thank you very much and welcome to our community!

In order to merge your contribution, you 'll have to complete all tasks in the checklist above!
Let us know if you need help with any of them, we will be more than happy to assist you.

**Comment by WaylonWalker** [comment]
Looks like you already took care of the `Type` for me @tsanikgr, Thank You.  I can add to the `Release.md` easily.  

I have a simple docstring in it now.  I will add the example above to it.  Will the docstring automatically get picked up in the documentation, or will I need to add it manually?

I have not looked at the tests at all yet.  Do you have a catalog already there that I can test from?

**Comment by yetudada** [comment]
Hi @WaylonWalker! Thank you so much for spending time on this amazing PR. We've actually been working a solution to view and search for a runtime list of datasets and it might solve discoverability of your datasets in Jupyter Notebook. Could we maybe pause work on this PR while we work on the feature? If we don't solve the problem for you then we'd be happy to come back to this implementation. Let me know if this is okay? 

We're also going to place your thought contribution on our release notes.

**Comment by WaylonWalker** [comment]
@yetudada Great, I'll close this for now.  I have implemented a workaround in our environment.  Excited to see the official solution get released.

**Comment by yetudada** [comment]
@WaylonWalker We have `kedro 0.14.3` out which just released this feature! You'll see your name up on our [RELEASE.md](https://github.com/quantumblacklabs/kedro/blob/develop/RELEASE.md) notes. Thank you so much!

**Comment by WaylonWalker** [comment]
@yetudata Thanks for the shout out!  I am still monkey patching in my own query method into our kedro projects.  As the tab completion is very nice it does get tedious when you have many data sets flowing through many layers, under many different organizations.  Many times the part of the name that I want to match on is near the end of the data set as that is the part that makes it unique.  I am looking for an easy way to fuzzy match for larger projects with many data sets.

## Example

I put together a catalog with many data sets to show my use case, and how deeply nested the actual data set name can become.  This is something that I do many times per day and would like to hear any suggestions that you have.


io_query

**Comment by idanov** [comment]
The gif you have provided is an amazing example @WaylonWalker! Do you mind sharing how you created the gif, so hopefully more people start using it to demonstrate issues they face during development?

As for the `.query()` issue, we don't have plans to support that anytime soon, but starting with `kedro` 0.15, it will become a bit easier to use custom `DataCatalog` which will load all your datasets in your ipython session. So no need to monkey patch it anymore, and you can just implement a custom `DataCatalog` which will include this new method and your project will benefit of that in all kedro sessions. Please feel free to reach out if you need help how to do that.

**Comment by WaylonWalker** [comment]
I used [ScreenToGif](https://www.screentogif.com/).  It seems to be the best gif screef recorder for windows.  I have used it for a number of years and it has done me well.

I will be interested to see how this works in `0.15`

**Pull request closed without merging**
