### PR TITLE
[KED-996] Added Multiprocess to `run_node`

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Co-authored-by: Samuel Sinayoko <ss53g10@gmail.com>"

## Description
Added multiprocess to ``run_node``.
Related to  https://github.com/quantumblacklabs/kedro/issues/242

## Development notes
#242 

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [x] Added tests to cover my changes

## Notice

- [ ] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by samuelsinayoko** [comment]
Nice meeting you tonight @marcelotrevisani !

**Comment by marcelotrevisani** [comment]
> Nice meeting you tonight @marcelotrevisani ! Will try and check in over the next few days to help get the PR through.

It was nice to meet you too!
I just added to your user permissions to my fork so you will be able to push changes if you want to. I just saw that the linters are complaining.

Please accept to have permissions to push on my fork
https://github.com/marcelotrevisani/kedro/invitations

**Comment by limdauto** [comment]
@marcelotrevisani Thank you for the contribution. Could you check the legal notice box please?

**Comment by 921kiyo** [comment]
Addressed in https://github.com/quantumblacklabs/kedro/commit/a6ed5e8612e2ca34b4975965b63c54acc5f06558

**Pull request closed without merging**
