### PR TITLE
[KED-1689] Allow JSON strings in CLI `--params` value

### PR DESCRIPTION
**Pull request by nikhiltjoy**
## Description
This adds the ability to send JSON string input to the CLI.

## Development notes
I changed the cookiecutter to parse the string to JSON first, and if it doesn't succeed, it continues with the key:value logic. Tested locally with my own project

## Checklist

- [x] Read the [contributing](../CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](../RELEASE.md) file
- [ ] Added tests to cover my changes

## Notice

- [ ] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by mzjp2** [comment]
Thank you for raising this PR!

I remember having this discussion with @DmitriiDeriabinQB when he first introduced this functionality. He had some good points against introducing `json` parsing in CLI option values that he might like to share here. :)

**Comment by DmitriiDeriabinQB** [comment]
> Thank you for raising this PR!
> 
> I remember having this discussion with @DmitriiDeriabinQB when he first introduced this functionality. He had some good points against introducing `json` parsing in CLI option values that he might like to share here. :)

The main reason for not allowing JSON is to separate the workflows. The most supported workflow is to provide the parameters as JSON, YAML or any other form of configuration in `conf/` folder, which is then handled by `ConfigLoader` identically to any other project configuration.

Passing parameters via CLI _is_ supported, but only as an auxiliary mechanism to the first use case. If a user tries to pass anything that is more complex than a string or a number (including nested parameters) into a parameter via CLI, we believe they are doing something wrong and should rather use the core mechanism, especially since parameter overriding is supported via config environments.

**Comment by nikhiltjoyQB** [comment]
> > Thank you for raising this PR!
> > I remember having this discussion with @DmitriiDeriabinQB when he first introduced this functionality. He had some good points against introducing `json` parsing in CLI option values that he might like to share here. :)
> 
> The main reason for not allowing JSON is to separate the workflows. The most supported workflow is to provide the parameters as JSON, YAML or any other form of configuration in `conf/` folder, which is then handled by `ConfigLoader` identically to any other project configuration.
> 
> Passing parameters via CLI _is_ supported, but only as an auxiliary mechanism to the first use case. If a user tries to pass anything that is more complex than a string or a number (including nested parameters) into a parameter via CLI, we believe they are doing something wrong and should rather use the core mechanism, especially since parameter overriding is supported via config environments.

Yup, makes sense. I needed it for the use-case of passing a list in --params, and perhaps overriding stuff defined in globals.yml.

However, in this case, we don't need these lines:
https://github.com/quantumblacklabs/kedro/blob/88cf4a471f3b6610360aea6f22de62219fb9112c/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L123-L124

The CLI command only accepts str inputs:
https://github.com/quantumblacklabs/kedro/blob/88cf4a471f3b6610360aea6f22de62219fb9112c/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L190-L192

**Comment by mzjp2** [comment]
> > > Thank you for raising this PR!
> > > I remember having this discussion with @DmitriiDeriabinQB when he first introduced this functionality. He had some good points against introducing `json` parsing in CLI option values that he might like to share here. :)
> > 
> > 
> > The main reason for not allowing JSON is to separate the workflows. The most supported workflow is to provide the parameters as JSON, YAML or any other form of configuration in `conf/` folder, which is then handled by `ConfigLoader` identically to any other project configuration.
> > Passing parameters via CLI _is_ supported, but only as an auxiliary mechanism to the first use case. If a user tries to pass anything that is more complex than a string or a number (including nested parameters) into a parameter via CLI, we believe they are doing something wrong and should rather use the core mechanism, especially since parameter overriding is supported via config environments.
> 
> Yup, makes sense. I needed it for the use-case of passing a list in --params, and perhaps overriding stuff defined in globals.yml.
> 
> However, in this case, we don't need these lines:
> 
> https://github.com/quantumblacklabs/kedro/blob/88cf4a471f3b6610360aea6f22de62219fb9112c/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L123-L124
> 
> The CLI command only accepts str inputs:
> 
> https://github.com/quantumblacklabs/kedro/blob/88cf4a471f3b6610360aea6f22de62219fb9112c/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L190-L192

I believe the reason for that there is to support `params` config passed in via the optional `kedro run --config <config_file>` option, which can specify a dictionary of parameters.

**Comment by mzjp2** [comment]
See this PR: https://github.com/quantumblacklabs/kedro/pull/226 :)

**Comment by deepyaman** [comment]
> See this PR: #226 :)

TIL

**Comment by DmitriiDeriabinQB** [comment]
@mzjp2 Very good point 👍 I already completely forgot about that PR 😄

**Comment by nikhiltjoy** [comment]
cool cool, good to know!

**Comment by mzjp2** [comment]
Thank you regardless for the contribution and hopefully you'll still contribute in the future! 🎉

**Pull request closed without merging**
