### PR TITLE
Fix example pipeline.py

### PR DESCRIPTION
**Pull request by dazzag24**
To make the example run you also need to import Pipeline from "kedro.pipeline" as well as node.

e.g. this:
`
from kedro.pipeline import node, Pipeline
`

otherwise the user will get a "NameError: name 'Pipeline' is not defined" error.

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking “Submit Pull Request”:

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
Why was this PR created?

## How has this been tested?
What testing strategies have you used?

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added new entries to the `RELEASE.md` file
- [ ] Added tests to cover my changes
- [ ] Assigned myself to the PR
- [ ] Added `Type` label to the PR

### CODE REVIEW

**Comment by 921kiyo** [comment]
Hi @dazzag24! Thank you for contributing to Kedro! We agree with your change and are happy to merge the change. Could you please tick the acknowledgement and see the checklist, so we can approve and merge the PR?

**Comment by dazzag24** [comment]
Hi,
I have ticked the acknowledgement box.  Have also ticked the relevant checkboxes...

**Comment by yetudada** [comment]
@dazzag24 Thank you for picking up this error! Could you add yourself to our `RELEASE.md` so that we can acknowledge your contribution?

**Comment by idanov** [comment]
@dazzag24 thanks a lot for your contribution! We hope you enjoyed the tutorial. We are always happy to receive feedback, so if you have any new ideas and suggestions, please feel free to share :)

**Pull request merged**
