### PR TITLE
[KED-1456] Provide docker container for kedro developer environment

### PR DESCRIPTION
**Pull request by neomatrix369**
## Description
Related to the issue #265 - given everyone has disparate python environments on our own favourite platforms, everything works fine till we introduce a new project, that's where docker can come in to rescue us!

## Development notes
Added two shell scripts and Dockerfile, no code changes made - isolated from the code base logic as such.

Adds to the setup and infra aspects of the project so developers can quickly get onboard with the project and not have to tackle development environment issues.

Pre-requisite: 
- require Docker installed, 
- internet (to build the image, one off) 
- enough storage space for the creation of a new docker image

## Checklist

- [X] Read the [contributing](/CONTRIBUTING.md) guidelines
- [ ] ~Opened this PR as a 'Draft Pull Request' if it is work-in-progress~
- [ ] Updated the documentation to reflect the code changes
- [X] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [ ] ~Added tests to cover my changes~

## Notice

- [X] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Please let me know what doc files you would like me to amend, in addition to the ones I have amended in this PR - in order to make sure users know they can run the shell scripts to build and run the docker container.

**Comment by neomatrix369** [comment]
I'm also happy and open to feedback on how you think the end-users should use these scripts - atm it's simple and basic, which I think should be a good start and we can build on top of it.

**Comment by neomatrix369** [comment]
Happy to discuss this further, if any doubts or suggestions. 
(conflicts occurring on this PR is due to PR #270)

**Comment by mzjp2** [comment]
Hey! 

Thanks for raising this PR and sorry for the delay in getting back to you. We've had an internal discussion about this and decided that we'd instead focus on making the development requirements more minimal, rather than introducing a docker image. You can now run tests and get started on contributing without Spark installed, which was a major impediment before.

I'll go ahead and close this, but thank you again for the PR and discussion. :)

**Pull request closed without merging**
