### PR TITLE
Clean up permanently redirected links in documentation

### PR DESCRIPTION
**Pull request by mzjp2**
## Description
My build on #671 was failing because of a broken link in the documentation, so I thought I'd come in here and clean things up a little, from replacing permanently redirected links with their (usually nicer and more canonical) new home or fixing outright incorrect links.

Note: I didn't know this linkchecker existed, think it's really cool and will help stave off all the issues about links being broken. Kudos for introducing it!

## Development notes
* Changed name of the CircleCI job from `Build docs` to `Check for broken links` so it's the job list is differentiated from the actual doc building run.
* Replaced permanently redirected links with their (usually nicer and more canonical) new homes, examples include:
  * `https://github.com/timothycrosley/isort` -> `https://github.com/PyCQA/isort`
  * `https://curl.haxx.se/windows/` -> `https://curl.se/windows/`
  * `http://*` -> `https://*` (wherever `https` is supported - which was everywhere in this case)
* Fixed the following broken or incorrect links
  * `https://www.anaconda.com/download/` -> `https://www.anaconda.com/products/individual#Downloads`
  * `https://jupyter-notebook.readthedocs.io/en/stable/changelog.html#cell-tags` -> `https://jupyter-notebook.readthedocs.io/en/stable/changelog.html#release-5-0-0` (the best reference I could find, they don't mention tags anywhere else in their docs). The `#cell-tags` anchor genuinely doesn't exist on that page.

From what I could tell, one of the big culprits for the 'too-many-redirects' and overall flakiness of the build was the `github.com/*` links. There are a large number of github links in the codebase and when the linkchecker goes over a cluster of them quickly, GH complains and rate limits us.

For now, I've followed the existing pattern and added semi-random links to the ignore list, but it might be worth adding the `github.com/*` regex to the list (although the trade-off may be too large, up to you!)

## Checklist

- [x] Read the [contributing](https://github.com/quantumblacklabs/kedro/blob/master/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md) file
- [x] Added tests to cover my changes

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by mzjp2** [comment]
For what it's worth, the tests have passed 3 times consecutively now :)

**Review by MerelTheisenQB — APPROVED** [review]
This is great, thanks @mzjp2 ! I'm hoping you didn't stay up all night going through those links manually 😜

**Comment by MerelTheisenQB** [comment]
Maybe it's actually worth adding `github.com/*` regex to the `linkcheck_ignore` list. The last build has failed again because of a Github link..

**Comment by mzjp2** [comment]
> Maybe it's actually worth adding `github.com/*` regex to the `linkcheck_ignore` list. The last build has failed again because of a Github link..

done!

**Review by yetudada — APPROVED** [review]
Well done @mzjp2! 🎉

**Pull request merged**
